
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "web_detector_rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
scraper = "0.19"
ahash = "0.8"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
