/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 主函数：检测所有列表容器 */
export declare function detectLists(html: string): Array<ListContainer>

/** 单个列表容器的结果 */
export interface ListContainer {
  selector: string
  itemCount: number
  score: number
}

export declare function plus100(input: number): number
